project_id = "otjtbhrwoxhdsxfvoigr"

[functions.nominatim-geocode]
verify_jwt = false

[functions.yelp-restaurant]
verify_jwt = false

[functions.opentable-reservation]
verify_jwt = false

[functions.nearby-restaurants]
verify_jwt = false

[functions.sync-restaurants]
verify_jwt = false

[functions.seed-restaurants]
verify_jwt = false

[functions.documenu-menu]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = true

[functions.analyze-patterns-notify]
verify_jwt = false
