project_id = "otjtbhrwoxhdsxfvoigr"

[functions.yelp-restaurant]
verify_jwt = false

[functions.opentable-reservation]
verify_jwt = false

[functions.nearby-restaurants]
verify_jwt = false

[functions.sync-restaurants]
verify_jwt = false

[functions.seed-restaurants]
verify_jwt = false
